### ISSUE TITLE
dictionary/web : LEARNING: add MariaDB jta data source

### ISSUE THREAD

**Issue by rxue** [rxue/dictionary#110]

**Comment by rxue** [comment]
mariadb docker container could not start successfully, ports cannot be assigned => probably because the docker image with the `latest` tag has problem

=>

**TODO** : change to the version with older tag

**Comment by rxue** [comment]
since use of `*-ds.xml` is deprecated based on the `WARN` log: `WARN  [org.jboss.as.connector] (MSC service thread 1-4) WFLYJCA0091: -ds.xml file deployments are deprecated. Support may be removed in a future version.`

=> configure `datasource` on the server side on base of https://docs.wildfly.org/28/Getting_Started_Guide.html#modifying-the-example-datasource

**Comment by rxue** [comment]
Mariadb database connection refused:

     Caused by: java.sql.SQLNonTransientConnectionException: Socket fail to connect to host:address=(host=localhost)(port=3306)(type=primary). Connection refused
     	at org.mariadb.jdbc//org.mariadb.jdbc.client.impl.ConnectionHelper.connectSocket(ConnectionHelper.java:137)
     	at org.mariadb.jdbc//org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:99)
     	at org.mariadb.jdbc//org.mariadb.jdbc.Driver.connect(Driver.java:70)
     	at org.mariadb.jdbc//org.mariadb.jdbc.Driver.connect(Driver.java:101)
     	at org.mariadb.jdbc//org.mariadb.jdbc.Driver.connect(Driver.java:27)
     	at org.jboss.ironjacamar.jdbcadapters@1.5.9.Final//org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:335)
     	... 37 more
     Caused by: java.net.ConnectException: Connection refused
     	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
     	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
     	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
     	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
     	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
     	at java.base/java.net.Socket.connect(Socket.java:633)
     	at org.mariadb.jdbc//org.mariadb.jdbc.client.impl.ConnectionHelper.connectSocket(ConnectionHelper.java:131)
     	... 42 more

**Comment by rxue** [comment]
got error cause:

     Caused by: java.sql.SQLNonTransientConnectionException: Socket fail to connect to host:address=(host=mariadb)(port=3306)(type=primary). mariadb
     	at org.mariadb.jdbc//org.mariadb.jdbc.client.impl.ConnectionHelper.connectSocket(ConnectionHelper.java:137)
     	at org.mariadb.jdbc//org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:99)
     	at org.mariadb.jdbc//org.mariadb.jdbc.Driver.connect(Driver.java:70)
     	at org.mariadb.jdbc//org.mariadb.jdbc.Driver.connect(Driver.java:101)
     	at org.mariadb.jdbc//org.mariadb.jdbc.Driver.connect(Driver.java:27)
     	at org.jboss.ironjacamar.jdbcadapters@1.5.9.Final//org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:335)
     	... 37 more
     Caused by: java.net.UnknownHostException: mariadb
     	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
     	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
     	at java.base/java.net.Socket.connect(Socket.java:633)
     	at org.mariadb.jdbc//org.mariadb.jdbc.client.impl.ConnectionHelper.connectSocket(ConnectionHelper.java:131)
     	... 42 more

**Comment by rxue** [comment]
encountered error:

     Caused by: java.sql.SQLSyntaxErrorException: (conn=227) DROP command denied to user 'root'@'172.19.0.3' for table 'Explanation'
     	at org.mariadb.jdbc//org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:282)
     	at org.mariadb.jdbc//org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
     	at org.mariadb.jdbc//org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:134)
     	at org.mariadb.jdbc//org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:883)
     	at org.mariadb.jdbc//org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:822)
     	at org.mariadb.jdbc//org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:741)
     	at org.mariadb.jdbc//org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:665)
     	at org.mariadb.jdbc//org.mariadb.jdbc.Statement.executeInternal(Statement.java:956)
     	at org.mariadb.jdbc//org.mariadb.jdbc.Statement.execute(Statement.java:1082)
     	at org.mariadb.jdbc//org.mariadb.jdbc.Statement.execute(Statement.java:474)
     	at org.jboss.ironjacamar.jdbcadapters@1.5.9.Final//org.jboss.jca.adapters.jdbc.WrappedStatement.execute(WrappedStatement.java:198)
     	at org.hibernate@6.1.5.Final//org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:54)
     	... 25 more

Solution reference: https://stackoverflow.com/questions/5016505/mysql-grant-all-privileges-on-database/5016587#5016587

**Comment by rxue** [comment]
encountered drop sequence error:

     Caused by: java.sql.SQLSyntaxErrorException: (conn=6) Unknown SEQUENCE: 'dictionary.explanation_id_seq'
     	at org.mariadb.jdbc//org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:282)
     	at org.mariadb.jdbc//org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
     	at org.mariadb.jdbc//org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:134)
     	at org.mariadb.jdbc//org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:883)
     	at org.mariadb.jdbc//org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:822)
     	at org.mariadb.jdbc//org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:741)
     	at org.mariadb.jdbc//org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:665)
     	at org.mariadb.jdbc//org.mariadb.jdbc.Statement.executeInternal(Statement.java:956)
     	at org.mariadb.jdbc//org.mariadb.jdbc.Statement.execute(Statement.java:1082)
     	at org.mariadb.jdbc//org.mariadb.jdbc.Statement.execute(Statement.java:474)
     	at org.jboss.ironjacamar.jdbcadapters@1.5.9.Final//org.jboss.jca.adapters.jdbc.WrappedStatement.execute(WrappedStatement.java:198)
     	at org.hibernate@6.1.5.Final//org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:54)
     	... 25 more
