### ISSUE TITLE
New feature: make use of session to store searched words on the search page by means of observer pattern (event)

### ISSUE THREAD

**Issue by rxue** [rxue/dictionary#23]

**Comment by rxue** [comment]
Encountered error:

    05:43:44,831 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service jboss.deployment.unit."dictionary.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."dictionary.war".WeldStartService: Failed to start service
    	at org.jboss.msc@1.4.12.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1731)
    	at org.jboss.msc@1.4.12.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
    	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
    	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
    	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
    	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-000072: Bean declaring a passivating scope must be passivation capable.  Bean:  Managed Bean [class rx.dictionary.ui.jsf.search.SearchObserver] with qualifiers [@Any @Default]
    	at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.bean.ManagedBean.checkType(ManagedBean.java:220)
    	at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.bean.AbstractBean.initializeAfterBeanDiscovery(AbstractBean.java:108)
    	at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.bean.ManagedBean.initializeAfterBeanDiscovery(ManagedBean.java:124)
    	at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.bootstrap.ConcurrentBeanDeployer$AfterBeanDiscoveryInitializerFactory.doWork(ConcurrentBeanDeployer.java:111)
    	at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.bootstrap.ConcurrentBeanDeployer$AfterBeanDiscoveryInitializerFactory.doWork(ConcurrentBeanDeployer.java:102)
    	at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
    	at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
    	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
    
    05:43:44,842 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "dictionary.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"dictionary.war\".WeldStartService" => "Failed to start service
        Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-000072: Bean declaring a passivating scope must be passivation capable.  Bean:  Managed Bean [class rx.dictionary.ui.jsf.search.SearchObserver] with qualifiers [@Any @Default]"}}
    05:43:45,006 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 45) WFLYSRV0010: Deployed "dictionary.war" (runtime-name : "dictionary.war")
    05:43:45,008 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
    WFLYCTL0186:   Services which failed to start:      service jboss.deployment.unit."dictionary.war".WeldStartService: Failed to start service
    WFLYCTL0448: 17 additional services are down due to their dependencies being missing or failed
    05:43:45,074 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
    05:43:45,077 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Full 24.0.0.Final (WildFly Core 16.0.0.Final) started (with errors) in 7480ms - Started 454 of 657 services (21 services failed or missing dependencies, 349 services are lazy, passive or on-demand)

**Comment by rxue** [comment]
search history can be displayed but just in the object hashcode form
