### ISSUE TITLE
Apply the message broker pattern: add a new (the 3rd) separate Wildfly server for the back-office work, i.e. handling incoming message from queues or topics in the broker

### ISSUE THREAD

**Issue by rxue** [rxue/dictionary#32]
`TODO`

1. Initialize a new project - backoffice

**Comment by rxue** [comment]
atm connect to the activemq embedded in the Wildfly is difficult to configure => ON HOLD

**Comment by rxue** [comment]
encountered error during backoffice Wildfly Docker container start up:

        | 22:07:26,956 ERROR [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0055: Caught exception during boot: org.jboss.as.controller.persistence.ConfigurationPersistenceException: WFLYCTL0085: Failed to parse configuration
        | 	at org.jboss.as.controller@18.1.1.Final//org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:137)
        | 	at org.jboss.as.server@18.1.1.Final//org.jboss.as.server.ServerService.boot(ServerService.java:405)
        | 	at org.jboss.as.controller@18.1.1.Final//org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:473)
        | 	at java.base/java.lang.Thread.run(Thread.java:834)
        | Caused by: javax.xml.stream.XMLStreamException: WFLYDM0145: Security realms are no longer supported, please remove them from the configuration.
        | 	at org.jboss.as.domain-management@18.1.1.Final//org.jboss.as.domain.management.parsing.ManagementXml_5.parseManagement(ManagementXml_5.java:94)
        | 	at org.jboss.as.server@18.1.1.Final//org.jboss.as.server.parsing.StandaloneXml_11.readServerElement(StandaloneXml_11.java:219)
        | 	at org.jboss.as.server@18.1.1.Final//org.jboss.as.server.parsing.StandaloneXml_11.readElement(StandaloneXml_11.java:123)
        | 	at org.jboss.as.server@18.1.1.Final//org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:127)
        | 	at org.jboss.as.server@18.1.1.Final//org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:52)
        | 	at org.jboss.staxmapper@1.3.0.Final//org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:122)
        | 	at org.jboss.staxmapper@1.3.0.Final//org.jboss.staxmapper.XMLMapperImpl.parseDocument(XMLMapperImpl.java:76)
        | 	at org.jboss.as.controller@18.1.1.Final//org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:126)
        | 	... 3 more
        | 
        | 22:07:26,957 FATAL [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details. - Server configuration file in use: standalone-full.xml
