### ISSUE TITLE
backoffice: Make a simple jsf page for uploading multiple files concurrently on the server side

### ISSUE THREAD

**Issue by rxue** [rxue/dictionary#36]

**Comment by rxue** [comment]
Bug: jsf page cannot be rendered. with the .xhtml as the request, the Chrome browser's source code is exactly the jsf code other than the rendered pure html

**Comment by rxue** [comment]
Error when uploading large file:

     Caused by: io.undertow.server.RequestTooBigException: UT000020: Connection terminated as request was larger than 10485760
     	at io.undertow.core@2.2.17.Final//io.undertow.conduits.FixedLengthStreamSourceConduit.checkMaxSize(FixedLengthStreamSourceConduit.java:173)
     	at io.undertow.core@2.2.17.Final//io.undertow.conduits.FixedLengthStreamSourceConduit.read(FixedLengthStreamSourceConduit.java:236)
     	at org.jboss.xnio@3.8.7.Final//org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
     	at io.undertow.core@2.2.17.Final//io.undertow.channels.DetachableStreamSourceChannel.read(DetachableStreamSourceChannel.java:209)
     	at io.undertow.core@2.2.17.Final//io.undertow.server.HttpServerExchange$ReadDispatchChannel.read(HttpServerExchange.java:2430)
     	at org.jboss.xnio@3.8.7.Final//org.xnio.channels.Channels.readBlocking(Channels.java:344)
     	at io.undertow.servlet@2.2.17.Final//io.undertow.servlet.spec.ServletInputStreamImpl.readIntoBuffer(ServletInputStreamImpl.java:201)
     	at io.undertow.servlet@2.2.17.Final//io.undertow.servlet.spec.ServletInputStreamImpl.read(ServletInputStreamImpl.java:176)
     	at io.undertow.core@2.2.17.Final//io.undertow.server.handlers.form.MultiPartParserDefinition$MultiPartUploadHandler.parseBlocking(MultiPartParserDefinition.java:226)
     	at io.undertow.servlet@2.2.17.Final//io.undertow.servlet.spec.HttpServletRequestImpl.parseFormData(HttpServletRequestImpl.java:857)
     	... 64 more

**Comment by rxue** [comment]
Solution reference: https://stackoverflow.com/questions/73574931/how-to-solve-requesttoobigexception-ut000020-connection-terminated-as-request
