### ISSUE TITLE
Sub-task of #46: trial: use Wildfly in integration test 

### ISSUE THREAD

**Issue by rxue** [rxue/dictionary#49]
Parent:

Sub-task of #45: Add integration test with Arquillian before implementing the case-insentitive search functionality

1st **TODO** : figure out how to make integration test work with Java8, maven, JUnit4

**Comment by rxue** [comment]
java.lang.RuntimeException: WFLYEMB0014: Cannot load module org.jboss.logmanager from: local module loader @6572421 (finder: local module finder @6b81ce95 (roots: /home/rui/git/github/dictionary/web/target/wildfly-18.0.0.Final/modules,/home/rui/git/github/dictionary/web/target/wildfly-18.0.0.Final/modules/system/layers/base))
 	    	   at org.wildfly.core.embedded.EmbeddedProcessFactory.setupLoggingSystem(EmbeddedProcessFactory.java:325)
 	    	   at org.wildfly.core.embedded.EmbeddedProcessFactory.createStandaloneServer(EmbeddedProcessFactory.java:157)
 	    	   at org.wildfly.core.embedded.EmbeddedProcessFactory.createStandaloneServer(EmbeddedProcessFactory.java:139)
 	    	   at org.jboss.as.arquillian.container.embedded.EmbeddedDeployableContainer.setup(EmbeddedDeployableContainer.java:49)
 	    	   at org.jboss.as.arquillian.container.embedded.EmbeddedDeployableContainer.setup(EmbeddedDeployableContainer.java:35)
 	    	   at org.jboss.arquillian.container.impl.ContainerImpl.setup(ContainerImpl.java:181)
 	    	   at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$7.perform(ContainerLifecycleController.java:149)
 	    	   at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$7.perform(ContainerLifecycleController.java:145)
 	    	   at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.forContainer(ContainerLifecycleController.java:255)
 	    	   at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.setupContainer(ContainerLifecycleController.java:144)
 	    	   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	    	   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	    	   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	    	   at java.lang.reflect.Method.invoke(Method.java:498)
 	    	   at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
 	    	   at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
 	    	   at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
 	    	   at org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createContainerContext(ContainerDeploymentContextHandler.java:57)
 	    	   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	    	   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	    	   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	    	   at java.lang.reflect.Method.invoke(Method.java:498)
 	    	   at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
 	    	   at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
 	    	   at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:135)
 	    	   at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:115)
 	    	   at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
 	    	   at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$1.perform(ContainerLifecycleController.java:62)
 	    	   at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$1.perform(ContainerLifecycleController.java:55)
 	    	   at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.forEachContainer(ContainerLifecycleController.java:209)
 	    	   at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.setupContainers(ContainerLifecycleController.java:54)
 	    	   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	    	   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	    	   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	    	   at java.lang.reflect.Method.invoke(Method.java:498)
 	    	   at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
 	    	   at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
 	    	   at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
 	    	   at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:135)
 	    	   at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:115)
 	    	   at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
 	    	   at org.jboss.arquillian.container.test.impl.client.ContainerEventController.execute(ContainerEventController.java:85)
 	    	   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	    	   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	    	   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	    	   at java.lang.reflect.Method.invoke(Method.java:498)
 	    	   at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
 	    	   at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
 	    	   at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
 	    	   at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:65)
 	    	   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	    	   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	    	   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	    	   at java.lang.reflect.Method.invoke(Method.java:498)
 	    	   at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
 	    	   at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
 	    	   at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:135)
 	    	   at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:115)
 	    	   at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:68)
 	    	   at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:97)
 	    	   at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
 	    	   at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)
 	    	   at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
 	    	   at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
 	    	   at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
 	    	   at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
 	    	   at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
 	    	   at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
	Caused by: org.jboss.modules.ModuleLoadException: Error loading module from /home/rui/git/github/dictionary/web/target/wildfly-18.0.0.Final/modules/system/layers/base/org/jboss/logmanager/main/module.xml
 	    	   at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:300)
 	    	   at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:256)
 	    	   at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:190)
 	    	   at org.jboss.modules.LocalModuleFinder.parseModuleXmlFile(LocalModuleFinder.java:207)
 	    	   at org.jboss.modules.LocalModuleFinder.lambda$findModule$0(LocalModuleFinder.java:154)
 	    	   at java.security.AccessController.doPrivileged(Native Method)
 	    	   at org.jboss.modules.LocalModuleFinder.findModule(LocalModuleFinder.java:154)
 	    	   at org.jboss.modules.ModuleLoader.findModule0(ModuleLoader.java:684)
 	    	   at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:677)
 	    	   at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:487)
 	    	   at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:390)
 	    	   at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:283)
 	    	   at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:271)
 	    	   at org.wildfly.core.embedded.EmbeddedProcessFactory.setupLoggingSystem(EmbeddedProcessFactory.java:323)
 	    	   ... 67 more
	Caused by: org.jboss.modules.xml.XmlPullParserException: Unexpected content of type 'element start' named 'module', text is: '<module name="org.jboss.logmanager" xmlns="urn:jboss:module:1.8">' (position: START_TAG seen ...\n<module name="org.jboss.logmanager" xmlns="urn:jboss:module:1.8">... @23:66) 
 	    	   at org.jboss.modules.xml.ModuleXmlParser.unexpectedContent(ModuleXmlParser.java:329)
 	    	   at org.jboss.modules.xml.ModuleXmlParser.validateNamespace(ModuleXmlParser.java:383)
 	    	   at org.jboss.modules.xml.ModuleXmlParser.parseDocument(ModuleXmlParser.java:413)
 	    	   at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:298)
 	    	   ... 80 more

**Comment by rxue** [comment]
continue on a new issue:

[Sub-task of #49: make integration test with wildfly-arquillian-container-remote and Docker](https://github.com/rxue/dictionary/issues/50)
